version: '3.1'

services:
  web:
    build: .
    ports:
      - 8081:8081
    environment:
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASSWORD: example
    command: "uvicorn main:app --host 0.0.0.0 --port 8001"

  tg_bot:
      build: .
      environment:
        API_TOKEN: "8177058610:AAF0PPYOtw39CHOLoADzx4MW8zNSRYwkLwQ"
        MONGO_HOST: mongo
        MONGO_USER: root
        MONGO_PASSWORD: example
      command: "python3 tg_bot.py"

  mongo:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - 27017:27017
    hostname: mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
